apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  labels:
    app: redis-exporter
spec:
  type: NodePort
  selector:
    app: redis-exporter
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
